export const defaultFlashcards = [
  { english: "Apple", hindi: "सेब", nextReview: 0, lastDifficulty: null },
  {
    english: "Good morning",
    hindi: "सुप्रभात",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "How are you?",
    hindi: "आप कैसे हैं?",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Thank you",
    hindi: "धन्यवाद",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "What is your name?",
    hindi: "आपका नाम क्या है?",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Good night",
    hindi: "शुभ रात्रि",
    nextReview: 0,
    lastDifficulty: null,
  },
  { english: "Yes", hindi: "हाँ", nextReview: 0, lastDifficulty: null },
  { english: "No", hindi: "नहीं", nextReview: 0, lastDifficulty: null },
  { english: "Please", hindi: "कृपया", nextReview: 0, lastDifficulty: null },
  {
    english: "Sorry",
    hindi: "माफ़ कीजिए",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Excuse me",
    hindi: "माफ़ कीजिए",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "I am fine",
    hindi: "मैं ठीक हूँ",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Nice to meet you",
    hindi: "आपसे मिलकर खुशी हुई",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Where are you?",
    hindi: "आप कहाँ हैं?",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Come here",
    hindi: "यहाँ आओ",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Go there",
    hindi: "वहाँ जाओ",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Sit down",
    hindi: "बैठ जाइए",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Stand up",
    hindi: "खड़े हो जाइए",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "I don't understand",
    hindi: "मैं नहीं समझा",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Can you help me?",
    hindi: "क्या आप मेरी मदद कर सकते हैं?",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "What time is it?",
    hindi: "समय क्या हुआ है?",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "I am hungry",
    hindi: "मुझे भूख लगी है",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "I am thirsty",
    hindi: "मुझे प्यास लगी है",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "I love you",
    hindi: "मैं तुमसे प्यार करता हूँ",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "What happened?",
    hindi: "क्या हुआ?",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "I don't know",
    hindi: "मुझे नहीं पता",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Call me",
    hindi: "मुझे फोन करो",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Wait a minute",
    hindi: "एक मिनट रुकिए",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "What are you doing?",
    hindi: "आप क्या कर रहे हैं?",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "Let's go",
    hindi: "चलो चलते हैं",
    nextReview: 0,
    lastDifficulty: null,
  },
  {
    english: "I am tired",
    hindi: "मैं थक गया हूँ",
    nextReview: 0,
    lastDifficulty: null,
  },
];
